### ISSUE TITLE
sow deploy -A: errors on exec: exec: "aws-iam-authenticator": executable file not found in $PATH

### ISSUE THREAD

**Issue by flexuser** [gardener/garden-setup#101]
I am trying to deploy gardener on AWS EKS. I have created Kubeconfig file that works well with kubectl and i get proper responses from EKS, but with gardener i am getting the following error message:

```
[root]# sow deploy tiller
*****************************
*** sowing species tiller
Plugin: kubectl[deploy] (/sow/plugins/kubectl/plugin)
manifest for ServiceAccount(v1): kube-system/tiller
error: unable to recognize "/mounted/root/landscape/gen/tiller/kubectl/manifests/0-0-ServiceAccount.kube-system.tiller.yaml": Get https://XYZ/api?timeout=32s: getting credentials: exec: exec: "aws-iam-authenticator": executable file not found in $PATH
command failed, waiting for 15 seconds and trying again (4 times)
```
I have that file in my PATH variable: /root/bin/aws-iam-authenticator
`[root@ landscape]# echo $PATH
/root/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/sow/docker/bin:/usr/local/bin`

I am not sure what wrong am doing:

sow order -A command works fine for me

Please can somebody suggest what wrong am doing?

Regards,
Jay

**Comment by Diaphteiros** [comment]
Hey, sorry for the late answer.

The `sow` tool comes with a docker image that includes its dependencies so you don't have to provide them. If you inspect the repository, you will find two `sow` files: one at `bin/sow` and one at `docker/bin/sow`. The first one is the actual `sow` script, but it needs lots of dependencies (e.g. `kubectl`, `git`, `terraform`, ...). The second one is a wrapper script that starts a docker container containing all the dependencies, mounts your current working directory in that container and then executes your command in there. This way, you only need docker, as all other dependencies are inside the container.

I assume that you started the containerized version of `sow`, which doesn't include the aws-iam-authenticator, therefore you get the error.
To resolve this, you could install the dependencies (you can check the dockerfile for that) and use the script at `bin/sow` directly. **However**, Gardener itself does not support cloudprovider-specific authentication in the kubeconfig.

Therefore you should instead try to get a kubeconfig that doesn't use provider-specific authentication.
