### ISSUE TITLE
Allow custom domain URL for the dashboard (including certificate)

### ISSUE THREAD

**Issue by kayrus** [gardener/garden-setup#102]
**What would you like to be added**:

Add an ability to set an alias to the dashboard URL. 

**Why is this needed**:

The current default domain certificate is `*.ingress.mydomain`, but there is no option to specify an alias, e.g. `dashboard.mydomain`.

https://github.com/gardener/garden-setup/blob/ddeedcac31ea5c6601ed58c3c58a2cba8447b95a/components/cert-manager/cert/deployment.yaml

**Comment by Diaphteiros** [comment]
This has been implemented, but not yet released: https://github.com/gardener/garden-setup/commit/65db6cc4bbfb9c918273796d87d9aead510253d2
Will most probably be included in release 1.17.0. I will close the issue once it is released.
