### ISSUE TITLE
How to set Shoot cluster's Pod/Service CIDR when deploying via auto-installer 

### ISSUE THREAD

**Issue by gauravbist** [gardener/garden-setup#141]
I am trying to install Gardener on existing Kubernetes Cluster (configured via KOPS) via automatic installer (https://gardener.cloud/installer/).

But I am facing an issue: "100.64.0.0/13": must not be a subset of "spec.networks.shootDefaults.services" ("100.64.0.0/13")

Tried with different subnet (100.80.0.0/11) too, then it gives error:
Error: release gardener failed: Service "gardener-apiserver" is invalid: spec.clusterIP: Invalid value: "100.80.0.20": provided IP is not in the valid range. The range of valid IPs is 100.64.0.0/13

As per the ticket gardener/gardener#1386  "Shoot pod/service CIDR defaults per seed",  "It is now possible to specify shoot default pod/service CIDRs **per seed**. Please configure `spec.networks.shootDefaults` on your `Seed` resources if you want to use this."

But I am not able to understand how to configure the same when using the automatic installer (https://gardener.cloud/installer/).

Please help me to achieve a successful deployment of Gardner on existing Kubernetes Cluster (configured via Kops).

**Comment by rfranzke** [comment]
@Diaphteiros can you help out?

**Comment by Diaphteiros** [comment]
@gauravbist The automated installer that you link to is meant to provide an visual overlay for garden-setup (this project) and abstract the complexity of creating the config file (acre.yaml) by yourself. The downside of this is that it strongly restricts the possible configurations - the garden-setup installer supports only a very small subset of the configuration options that garden-setup offers.
However, the `shootDefaults` networks are currently not configurable in garden-setup either. For garden-setup 1.18.0, you would need to modify it in the [code](https://github.com/gardener/garden-setup/blob/1.18.0/components/gardencontent/seeds/manifests/seed_manifest.yaml#L51-L53) directly before running `sow deploy`. 

I'll leave this issue open and make the networks configurable in garden-setup with one of the next releases.

**Comment by Diaphteiros** [comment]
Resolved with #154
