### ISSUE TITLE
Deletion of a garden cluster does not cleanup shoots

### ISSUE THREAD

**Issue by schrodit** [gardener/garden-setup#2]
When a gardener cluster contains shoots and garden-setup wants to delete it the deletion process stuck if there are still shoots in the cluster.
The garden-setup should rather delete all shoots first before deleting the cluster.

**Comment by Diaphteiros** [comment]
This is resolved with https://github.com/gardener/garden-setup/commit/1e523347a313db1e1fcd085a6e9e2c1598eee28b and https://github.com/gardener/garden-setup/commit/d2005f812a8a8f426178b7b4165aa605370556a2

A new plugin has been added to the components responsible for the core project, the initial seed, and the gardener itself. The plugin will check if deleting the component conflicts with an existing shoot and will abort the deletion with an error message, if so.
