### ISSUE TITLE
Support for new AWS region us-gov-west-1

### ISSUE THREAD

**Issue by mward29** [gardener/garden-setup#203]
**What would you like to be added**:
While there are AMIs setup for us-gov-west-1 AWS region, there is no profile setup.

**Why is this needed**:
Adding the profile will allow deploying Gardener to us-gov-west-1 without the user having to specifically define the region in their acre.yaml.

**Comment by mward29** [comment]
I will submit a PR for this.

**Comment by Diaphteiros** [comment]
Resolved by #206
