### ISSUE TITLE
cloudflare-dns not found error while sowing species gardener/virtual

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [gardener/garden-setup#209]
**What happened**:
I am trying to deploy Gardener onto my cluster and things went well until `sowing species gardener/virtual` where I got the following error
```
2020/05/02 08:35:22 error generating manifest: unresolved nodes:
        (( *(.dns_credentials.[provider]) ))    in /mounted/home/sayak/landscape/crop/components/gardener/virtual/deployment.yaml       gardener.values.global.defaultDomains.[0].credentials  ()      *'cloudflare-dns' not found
        (( *(.dns_credentials.[provider]) ))    in /mounted/home/sayak/landscape/crop/components/gardener/virtual/deployment.yaml       gardener.values.global.internalDomain.credentials      ()      *'cloudflare-dns' not found
        (( *(.dns_credentials.[.landscape.dns.type]) )) in /mounted/home/sayak/landscape/crop/components/gardener/virtual/deployment.yaml       settings.dns_credentials       ()      *'cloudflare-dns' not found
error classification:
 *: error in local dynaml expression
 @: dependent of or involved in a cycle
 -: depending on a node with an error
Error: processing deployment.yaml
```
**What you expected to happen**:
I expected the cloudflare dns to work smoothly since it was added in 1.29.0
**How to reproduce it (as minimally and precisely as possible)**:
I think just trying to make a fresh deployment with cloudflare dns would trigger this
**Anything else we need to know?**:
I think I have somewhat found the issue and it is in https://github.com/gardener/garden-setup/blob/87b13681976fbf4ec92805fb4f4a632b50b3375b/components/gardener/virtual/deployment.yaml#L47 . Notice that the `dns_credentials` do not have `cloudflare-dns` as a key. I don't know if similar issues is present elsewhere.
**Environment**:

- Version of garden-setup 
1.31.0
- Versions of components (only needed if you overwrote the defaults)
- Where does the underlying base cluster come from and which operating system does it use?
AKS-Linux
- Which cloud provider is configured for the setup?
Azure
- Other:

**Comment by Diaphteiros** [comment]
Damn, you are right, I forgot to add this to the Gardener components. I'll have a look at your PR and where exactly the error comes from.
