### ISSUE TITLE
Deleting deployment with sow delete all deletes resource group under etcd.backup

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [gardener/garden-setup#211]
**What happened**:
In my `acre.yaml` I had setup the `etcd.backup.resourceGroup` as an existing resource group under which the cluster itself is present. Now while deleting I can see that sow is trying to delete this resource group. This resource group already has other resources like the cluster itself and deleting this resource group will delete the cluster itself.
**What you expected to happen**:
Deletion of the deployment shouldn't affect other existing resources.
**How to reproduce it (as minimally and precisely as possible)**:
1. Create a resource group in Azure and add any random resource to it.
2. Use this resource group as the resource group for etcd backup in the `acre.yaml` and deploy Gardener.
3. Delete this Gardener deployment.
4. The resource group along with the manually created resource is deleted.
**Anything else we need to know?**:
This is reproduced in Azure
**Environment**:

- Version of garden-setup
1.31.0
- Versions of components (only needed if you overwrote the defaults)
- Where does the underlying base cluster come from and which operating system does it use?
AKS-Linux
- Which cloud provider is configured for the setup?
Azure
- Other:

**Comment by Diaphteiros** [comment]
Unfortunately, there seems to be no simple way of telling terraform "create this, if it doesn't exist, but on deletion, don't delete it if you didn't create it". 
I haven't found a nice solution for this problem yet.

**Comment by SayakMukhopadhyay** [comment]
Then for the time being, I think a warning should be added in the docs. I can create a PR if that's ok.

**Comment by Diaphteiros** [comment]
Yeah, of course!

**Comment by berendt** [comment]
@Diaphteiros This one's done. I think the issue can be closed.

**Comment by Diaphteiros** [comment]
I left this issue open because we still don't have a solution, we just added a warning for the problem.
However, I don't think that this will be really solved anytime soon and since we are already working on the landscaper, we can just close the issue as well.
