### ISSUE TITLE
Add documentation for landscape.identity.issuerUrl and injection of redirectUrl for identity connectors

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [gardener/garden-setup#222]
**What would you like to be added**:
1. I have noticed in https://github.com/gardener/garden-setup/blob/4ec58b346d6bf622249089019dc8917481fb9a36/components/identity/deployment.yaml#L46 that `.landscape.identity.issuerUrl` is getting used which means that one can configure the `issuerUrl` in their `acre.yaml`. As such, documentation as to its functionalities and catches would be nice
2. I have also noticed that a `redirectURI` is injected in https://github.com/gardener/garden-setup/blob/4ec58b346d6bf622249089019dc8917481fb9a36/components/identity/deployment.yaml#L34 and I guess this can inject the `redirectURI` field in `identity.connectors.config.redirectURL`. This feature should also be documented.
**Why is this needed**:
1. Being able to configure the issuer url would be useful but documentation is needed so we are sure as to its exact functionalities
2. Injection of redirect url is also another great feature which if works as I guess would make addition of the `redirectURI` in https://github.com/gardener/garden-setup/blob/master/docs/extended/identity.md#variant-2-oidc-connector unnecessary.

**Comment by SayakMukhopadhyay** [comment]
I can verify that deploying a cluster with `identity.connectors.config.redirectURI` not set still sets the `redirectURI` correctly in the deployed configmap.

**Comment by Diaphteiros** [comment]
I added the missing information to the identity documentation, see #223
