### ISSUE TITLE
Option in acre.yaml to enable the identity url

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [gardener/garden-setup#229]
**What would you like to be added**:
A single flag can be added in the `acre.yaml` to directly use the `identity_dns` as `issueUrl`.
**Why is this needed**:
Right now `issueUrl` is defined as https://github.com/gardener/garden-setup/blob/a9e3ab97a7392c68c9c1d24d7b00e8c38e212c70/components/identity/deployment.yaml#L46
This means that the `issueUrl` can be changed using `identity.issuerUrl` in the `acre.yaml` file. This is great if we want a totally custom URL but the downside is that if we want a url which uses the `landscape.domain`, we would still need to write the whole URL. Moreover there is a piece of code https://github.com/gardener/garden-setup/blob/a9e3ab97a7392c68c9c1d24d7b00e8c38e212c70/components/identity/deployment.yaml#L49
which is not used anywhere but satisfies the requirement. So, I suggest a flag in the `acre.yam`, something like `identity.useIdentityDNS: true` which would use `identity_dns` instead of `dashboard_dns`. The default can be `false` for backwards compatibility.

So the Line 46 above becomes

```
issuerUrl: (( .landscape.identity.useIdentityDNS == "true" ? "https://" identity_dns "/oidc" : .landscape.identity.issuerUrl || "https://" dashboard_dns "/oidc" ))
```

I am not sure about the correctness of the above expression but I hope I got the point across.

**Comment by Diaphteiros** [comment]
Hm, actually the acre.yaml file supports templating ([spiff++](https://github.com/mandelsoft/spiff), the same one that is used for the other documents). This means that you could achieve the wanted effect - overwriting the issuer URL without having to copy the whole domain - by setting `landscape.identity.issuerUrl` to something like `(( "myIdentityPrefix." landscape.domain ))`. 

Thus, I'm not sure we actually need this flag. @SayakMukhopadhyay what do you think?

**Comment by SayakMukhopadhyay** [comment]
Yeah, I am aware of the spiff++ templating in `acre.yaml` and my current scenario can be achived with so. But I was wondering if a more out of the box experience would be preferable. We were discussing in Slack as to how `identity_dns` was a hangover from when dex used to sit in a seperate subdomain and how it was dropped to handle self signed cert issues. 

That got me wondering as to why not reuse that variable by allowing the user to setup a flag. Essentially I am attempting at SSO on the monitoring dashboards with the intention of contributing upstream and as such I think the identity should sit in its own subdomain and should be configurable out of the box.

**Comment by Diaphteiros** [comment]
OK. I'll think about it, but this should be quite easy to add, so I'll probably do it ;-)

**Comment by Diaphteiros** [comment]
Hm, I tried to add this (https://github.com/gardener/garden-setup/commit/dcc5043d005211b197f43e2958934694a9446451), but I don't like the fact that this creates an inconsistent landscape - if activating this flag only changes the issuerUrl, then you can't login into the dashboard anymore. To get this to work properly, I probably need to add another ingress (for the identity domain) and adapt some configuration in the dashboard ...

**Comment by Diaphteiros** [comment]
I'll check this again after the weekend, if I have time.

**Comment by SayakMukhopadhyay** [comment]
> if activating this flag only changes the issuerUrl, then you can't login into the dashboard anymore.

Correct me if I am wrong but isn't the dashboard itself is using the `settings.issuerUrl`? Because setting `.landscape.identity.issuerUrl` is enough to redirect the dashboard to the correct identity endpoint. Moreover setting `.landscape.identity.issuerUrl` also generates the correct identity ingress.

So, in my head, this flag just simplifies the setting of `.landscape.identity.issuerUrl` to a variable that already exists.
