### ISSUE TITLE
cidr confilicts on aws 

### ISSUE THREAD

**Issue by knightXun** [gardener/garden-setup#251]
Garden-setup forbid pod and node use same cidr. But Aws eks will make pod and node using same cidr default, that make install fail. After I uninstall aws-cni plugins and replace it with calico, the install can continue. I suggest hint this in gardener docs for users: dont use default aws cni plugins and replace it with other cni.

**Comment by Diaphteiros** [comment]
@knightXun I added a small 'warning' to the documentation that the installation on EKS is somewhat troublesome. What do you think? See #264

**Comment by knightXun** [comment]
@Diaphteiros Let read this pr, I believe it is awesome.

**Comment by alittlec** [comment]
is it possible to extend the warning to include an example of which other cni to use and how to apply it?

**Comment by Diaphteiros** [comment]
@alittlec Unfortunately, I have never tried to use garden-setup on EKS or to replace the default EKS CNI, so I can't describe the process. @knightXun can you help here?

**Comment by knightXun** [comment]
@alittlec Hi man, Please don't try this on aws eks, You can use kops build a cluster on aws, and use garden-setup on it.
