### ISSUE TITLE
Update nginx ingress-controller

### ISSUE THREAD

**Issue by dergeberl** [gardener/garden-setup#278]
**What would you like to be added**:

Add a newer version of the nginx ingress-controller.
The current ingress-controller version in the garden-setup is the 0.20.0 (released in 2018).

I tested the newest release 0.34.1 (https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.34.1) and can`t find any problems after the update to the newer version.

In addition to the new image I had to change/add the following options:

- set the runAsUser to 101 
- add in the ClusterRole for the "ingresses" resource a second apiGroup "networking.k8s.io"

In the same step of the update I think it is a good idea to move the image_repo and image_tag to the versions section in the acre file.

Is there a reason for not update the ingress-controller? If not, I would provide a PR for the update.

**Why is this needed**:

The current ingress-controller version is very old.

**Comment by Diaphteiros** [comment]
No, there is no reason for the ingress controller not being updated except that I'm somewhat focused on keeping the Gardener and its extensions up to date and sometimes completely forget about third party dependencies. I would be happy if you could provide a PR for this.
