### ISSUE TITLE
Unable to deploy gardener

### ISSUE THREAD

**Issue by srinis-book** [gardener/garden-setup#30]
$ sow order -A
Unable to find image 'eu.gcr.io/gardener-project/sow:1.0.7-dev' locally
docker: Error response from daemon: manifest for eu.gcr.io/gardener-project/sow:1.0.7-dev not found.
See 'docker run --help'.

**Comment by dcherman** [comment]
Ran into the same problem, that image doesn't exist.  I ended up having to edit https://github.com/gardener/sow/blob/master/VERSION locally to refer to 1.0.6 which does exist.

**Comment by Diaphteiros** [comment]
You can build the image locally (just call `make`) and then it should work. 
However, we are currently discussing whether we can also upload the dev images, then it should work out of the box.

**Comment by Diaphteiros** [comment]
Solved with https://github.com/gardener/sow/commit/e2f476500d8a648f6c8314b0da9581cf07f3c350
