### ISSUE TITLE
Gardenet on Chameleon Cloud architecture

### ISSUE THREAD

**Issue by hfmartinez** [gardener/garden-setup#302]
Hi there, right now I'm installing Gardener in two Kubernetes clusters. The first one is allocated on a local server and the idea is to connect it via Gardener on a remote Kubernetes cluster which is located on Chameleon Cloud (an OpenStack iaas type).
While I was doing the introduction on Gardener, they asked for some credentials that I don't know how to get (and implement) on the following architecture.

![image](https://user-images.githubusercontent.com/49379467/93553709-fc706100-f973-11ea-989b-73c3b5706f0c.png)

I'll appreciate some help with it or some reference where I can find guidance on the process.

**Comment by Diaphteiros** [comment]
I'm not sure whether this scenario is currently supported, but then again, I'm also not sure what exactly you want to do.

> ... the idea is to connect it via Gardener ...

What do you mean with 'connect'?

The way I understand it, you have your Gardener running on the left hand side cluster ('local server') and want to be able to create shoot clusters in the chameleon cloud whose controlplane is hosted on the right hand side cluster?

If that is correct, you would have to create a cloudprofile for the chameleon cloud and register the right hand side cluster as a seed. Gardener, as well as garden-setup, support openstack, so in theory, this is possible. However, I don't know how the 'chameleon' openstack differs from the openstack that we are using, I have never heard of this before. If there are some relevant differences, the Gardener openstack extension might not be able to handle the chameleon cloud, which would mean that you have to write a 'chameleon extension' for Gardener first.

cc @rfranzke

**Comment by vasu1124** [comment]
@hfmartinez any update?
