### ISSUE TITLE
Registry service unreachable.

### ISSUE THREAD

**Issue by munnaeebd** [gardener/garden-setup#310]
**What happened**:

I am getting following error during --> sow deploy

$sow -v deploy -A

~~~
using path terraform
terraform init /mounted/root/gardener/landscape/crop/components/etcd/backupinfra/provider/swift

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Registry service unreachable.

This may indicate a network issue, or an issue with the requested Terraform Registry.


Error: registry service is unreachable, check https://status.hashicorp.com/ for status updates
~~~

# sow -v order -A
~~~
acre = /mounted/root/gardener/landscape
acre greenhouse = /mounted/root/gardener/landscape/crop
greenhouse = <main>
namespace
etcd/backupinfra
etcd/cluster
dns-controller
ingress-controller
cert-manager/controller
cert-manager/solver
cert-manager/cert
identity
kube-apiserver
gardener/virtual
gardener/runtime
gardener/extensions
gardencontent/profiles
gardencontent/gardenproject
gardencontent/seeds/soils
dashboard

~~~

I am using openstack provider. is there any way to skip etcd/backupinfra? 

swift is not available in our openstack so cant use. please advice.

**Comment by Diaphteiros** [comment]
I just merged a PR into master that allows deactivating the backup 😄 

For the virtual cluster etcd, just add `active: false` to `landscape.etcd.backup` in your acre.yaml. 
Please have in mind that you need to deactivate backup for each seed too, see https://github.com/gardener/garden-setup/blob/master/docs/extended/iaas.md#seed-backup for details.

I will have a look at the openstack terraform provider and close this issue after I have confirmed that it works.
