### ISSUE TITLE
Configuration of OpenStack CloudProfile

### ISSUE THREAD

**Issue by afritzler** [gardener/garden-setup#38]
**What would you like to be added**:
In the `acre.yaml`we should allow the user to configure the following things:

* Machine Image names
* Provider network
* Upcomming Provider pool Lbaas classes
* etc.

**Why is this needed**:
Since every OpenStack installation is different, we need a way to customize the way the `CloudProfile` will look like.

**Comment by afritzler** [comment]
Actually `.landscape.iaas.openstack.extensionConfig` seems to be the place to configure a custom profile.

**Comment by Diaphteiros** [comment]
Resolved with https://github.com/gardener/garden-setup/pull/49 / [release 1.3.0](https://github.com/gardener/garden-setup/releases/tag/1.3.0)

There is now also a small documentation showing an example of the openstack configuration: https://github.com/gardener/garden-setup/blob/master/docs/extended/iaas.md#openstack
