### ISSUE TITLE
Deploy another shoot as seed

### ISSUE THREAD

**Issue by schrodit** [gardener/garden-setup#4]
To test specific behavior of seeds it would be great when the gardener-setup creates a shoot and registers the existing seed as a soil and the created shoot as a seed.

Maybe make this behavior configurable as it is not needed in every use case.

**Comment by Diaphteiros** [comment]
fixed with #67 and documented [here](https://github.com/gardener/garden-setup/blob/master/docs/extended/iaas.md#shooted-seeds)
