### ISSUE TITLE
Support multiple cloudproviders

### ISSUE THREAD

**Issue by schrodit** [gardener/garden-setup#40]
**What would you like to be added**:
Add initial support (cloudprofile, secrets and extension controllers) for multiple cloudproviders.

**Why is this needed**:
This is needed to validate multiple cloudprovider with one gardener installation.

**Comment by Diaphteiros** [comment]
Resolved with https://github.com/gardener/garden-setup/pull/49 / [release 1.3.0](https://github.com/gardener/garden-setup/releases/tag/1.3.0)
