### ISSUE TITLE
Support cutomization of the cloudprofile

### ISSUE THREAD

**Issue by schrodit** [gardener/garden-setup#41]
**What would you like to be added**:
Add the feature to cutomize specific sections of the deployed cloudprofile (e.g. k8s versions)

**Why is this needed**:
This feature is needed if we want to validate new kubernetes versions (patch or minor) without modifying garden-setup

**Comment by Diaphteiros** [comment]
Resolved with https://github.com/gardener/garden-setup/pull/49 / [release 1.3.0](https://github.com/gardener/garden-setup/releases/tag/1.3.0)

See https://github.com/gardener/garden-setup/blob/master/docs/extended/iaas.md#overwriting-cloudprofiles for more information.
