### ISSUE TITLE
Update Cert-Manager to a recent version

### ISSUE THREAD

**Issue by christianhuening** [gardener/garden-setup#439]
**What would you like to be added**:
the version of cert manager being used is fairly outdated (0.13.x). We should update to cert-manager 1.3.x or newer
**Why is this needed**:
Newer cert-manager versions provide much better errors in cases where the rate limit with Lets Encrypt is hit etc. Also some handling changed and cert-manager got new features and bug fixes including some breaking changes.

**Comment by Diaphteiros** [comment]
fixed by #445
