### ISSUE TITLE
Add an ability to define initialseed cluster name

### ISSUE THREAD

**Issue by kayrus** [gardener/garden-setup#45]
**What would you like to be added**:

At the moment the root seed cluster name is based on the iaas type: https://github.com/gardener/garden-setup/blob/8aabff37e97554f60f13654035fb43064f663579/components/gardencontent/initialseed/deployment.yaml#L36

It would be great to have an independent name definition, e.g. `root` for the root Gardener cluster.

**Why is this needed**:

To avoid confusions while identifying the cluster purpose by its name.

**Comment by Diaphteiros** [comment]
Resolved with https://github.com/gardener/garden-setup/pull/49 / [release 1.3.0](https://github.com/gardener/garden-setup/releases/tag/1.3.0)
