### ISSUE TITLE
Add an ability to configure Gardener journal

### ISSUE THREAD

**Issue by kayrus** [gardener/garden-setup#46]
**What would you like to be added**:

Add an acre.yaml entry, that will configure these defaults:
* https://github.com/gardener/dashboard/blob/c0d2286c00b9db7ea2edc5dee28d0be41b68abb6/charts/gardener-dashboard/values.yaml#L63
* https://github.com/gardener/dashboard/blob/c0d2286c00b9db7ea2edc5dee28d0be41b68abb6/charts/gardener-dashboard/values.yaml#L74

**Why is this needed**:

To preconfigure journal feature in gardener dashboard using sow.

**Comment by Diaphteiros** [comment]
Resolved with https://github.com/gardener/garden-setup/pull/51
