### ISSUE TITLE
Gardener does not get cleaned up correctly if the previous deployment failed

### ISSUE THREAD

**Issue by schrodit** [gardener/garden-setup#57]
**What happened**:
Garden setup is unable to delete its deployed resources properly when garden-setup fails during creation before gardener resources (like shoots) can be deployed into the virtual api-server.
Garden-setup checks if there are any shoots left in the virtual apiserver before it is clenaed up. But when the apiserver is not aware of a resource like shoot the deletion fails with this error.
```
*** deleting species gardener/runtime
using local action script
Plugin: shoot-check[delete] (/tmp/garden/crop/plugins/shoot-check/plugin)
   using inline kubeconfig
Error: error: the server doesn't have a resource type "shoots"
```

**What you expected to happen**:
Garden-setup should cleanup correctly when shoots cannot be found or are unknown.

**Comment by Diaphteiros** [comment]
fixed with #68
