### ISSUE TITLE
cannot create Shoot Cluster from Gardener Dashboard

### ISSUE THREAD

**Issue by phongvu0403** [gardener/garden-setup#577]
I installed Gardener on my Kubernetes Landscape. My iaas is OpenStack. Components are installed successfully. But I am having problem in creating shoot cluster from Gardener Dashboard. I can click on create cluster, then adjust Cluster Details, Infrastructure Details, Worker, Add-Ons. But after confirm will create cluster, nothing happens. There isn't any seed cluster created. Can someone tell me how to fix this problem? If you want to know more about my setup example acre.yaml file, i will provide it. Thank advance!

**Comment by Diaphteiros** [comment]
Please have a look at your shoot cluster why it is not created. What does the error message say?
If the dashboard doesn't show any error, check your `shoot` resource. Please note that the Gardener-specific resources are not in your base cluster, but in the 'virtual' cluster, for which you need to use the kubeconfig at `export/kube-apiserver/kubeconfig`. With that kubeconfig, find your shoot and use `kubectl get` and/or `kubectl describe` on it to get some information about the problem.

**Comment by dat1041988** [comment]
@Diaphteiros
I have this error when creating shoot cluster:

Check required extensions failed (retry failed with context deadline exceeded, last error: extension controllers missing or unready: map[ControlPlane/openstack:{} Infrastructure/openstack:{} Worker/openstack:{}])

 Can you give me some advices?

**Comment by phongvu0403** [comment]
sorry, I had a mistake so I edited my issue. I failed right from the shoot cluster step on Dashboard. Can i create a shoot cluster from CLI eg gardenctl ( I can't find an option to create).

**Comment by Diaphteiros** [comment]
@dat1041988 This means that your openstack extension is not running. There are several things you can check:

- On the virtual cluster (I explained above where the kubeconfig can be found) there should be a `ControllerRegistration` for Openstack.
- There should also be one or more `ControllerInstallation` resources in your virtual cluster for openstack.
- On the seed cluster where your shoot is scheduled, there should be a namespace where the openstack extension is running. I don't know the exact name of this namespace, but the name should contain `extension` and `openstack` somehow. Does this namespace exist? Are the pods in this namespace running?

**Comment by Diaphteiros** [comment]
@phongvu0403 To create a shoot cluster without using the dashboard, simply apply a shoot manifest into the virtual cluster (the `shoot` resource doesn't exist in your base cluster, only in the virtual one, see above for the explanation).
Here is an example of a shoot manifest: https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml

**Comment by dat1041988** [comment]
Thanks @Diaphteiros 

![image](https://user-images.githubusercontent.com/42293819/127729057-c77214fa-a68e-4449-9920-e750e2cb70c3.png)

When i describe: k describe ControllerInstallation provider-openstack-kjs9s
Message:               condition ResourcesHealthy of managed resource garden/provider-openstack-kjs9s is Unknown: The health checks have not yet been executed for the current set of resources.

![image](https://user-images.githubusercontent.com/42293819/127729142-be74dba9-91a1-46a7-b025-889452f0ebc9.png)

**Comment by dat1041988** [comment]
I think i found the cause.
# k describe managedresources.resources.gardener.cloud provider-openstack-kjs9s -n garden
Message:               Could not apply all new resources: 1 error occurred: error during apply of object "storage.k8s.io/v1/StorageClass/default/cinder": StorageClass.storage.k8s.io "cinder" is invalid: volumeBindingMode: Invalid value: "Immediate": field is immutable

I got this situation because i tried to change etcd storage class garden.cloud-fast to my default storageclass (name "cinder" using CSI). I posted this issue: https://github.com/gardener/gardener-extension-provider-openstack/issues/321

So, another question:
Can i change storageclass from garden.cloud-fast to my storageclass? And If cannot, i got the issue with pvc in pending state. Do I have to install/config somethings to intree volume working with CSI already installed in my cluster?

Thanks!

**Comment by Diaphteiros** [comment]
Hm, that goes too deep into the specifics of the openstack extension, I don't know that, unfortunately.

**Comment by dat1041988** [comment]
Thanks!
I passed this error when using garden.cloud-fast default with intree cinder & enable CSI migration feature-gates.
