### ISSUE TITLE
sow deploy -A halts

### ISSUE THREAD

**Issue by Morriz** [gardener/garden-setup#65]
**What happened**:
`sow -A ` halts at
```bash
generating exports
*** species cert-manager/solver deployed

*****************************
*** sowing species cert-manager/cert
using local action script
Plugin: kubectl[deploy] (/sow/plugins/kubectl/plugin)
manifest for Certificate(certmanager.k8s.io/v1alpha1): garden/dashboard-identity-ingress
certificate.certmanager.k8s.io/dashboard-identity-ingress configured
cluster https://IPMASKED
  found deployed objects: 1
  found currect objects: 1
The export generation waits for the certificate, which may take some time.
generating exports
```

**What you expected to happen**:
for the installer to continue and finish

**How to reproduce it (as minimally and precisely as possible)**:
`cert-manager.server: live`

**Anything else we need to know?**:

**Environment**:

- Version of garden-setup (release or commit)
sow: 1.0.10-dev
- Versions of components (only needed if you overwrote the defaults)
- Where does the underlying base cluster come from and which operating system does it use?
gke (cos)
- Which cloud provider is configured for the setup?
gcp

- Other:

**Comment by Diaphteiros** [comment]
This indicates that the setup has problems getting your certificate. I need some more information for a more precise analysis:
- `kubectl describe` on the certificate resource `dashboard-identity-ingress` in namespace `garden`
- logs of the cert-manager pod

**Comment by Diaphteiros** [comment]
@Morriz I tried to reproduce the error using the current versions of `garden-setup` and `sow`, but everything worked flawlessly. Can you try it with the current versions or provide more information?

**Comment by Diaphteiros** [comment]
Closed due to inactivity.
