### ISSUE TITLE
sow deploy -A errors at bucket creation

### ISSUE THREAD

**Issue by Morriz** [gardener/garden-setup#66]
**What happened**:
```
google_storage_bucket.bucket: Creating...
  bucket_policy_only: "" => "<computed>"
  force_destroy:      "" => "true"
  location:           "" => "EU-WEST4"
  name:               "" => "xxxx-gardener-etcd-bucket"
  project:            "" => "<computed>"
  self_link:          "" => "<computed>"
  storage_class:      "" => "COLDLINE"
  url:                "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* google_storage_bucket.bucket: 1 error(s) occurred:

* google_storage_bucket.bucket: googleapi: Error 400: Invalid Value, invalid

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```
**What you expected to happen**:
the install to finish

**How to reproduce it (as minimally and precisely as possible)**:
`cert-manager.server: self-signed`

**Anything else we need to know?**:

**Environment**:

- Version of garden-setup (release or commit)
sow 1.0.10-dev
- Versions of components (only needed if you overwrote the defaults)
- Where does the underlying base cluster come from and which operating system does it use?
gke (cos)

- Which cloud provider is configured for the setup?
gcp

- Other:

**Comment by Diaphteiros** [comment]
@Morriz I tried to reproduce the error using the current versions of `garden-setup` and `sow`, but everything worked flawlessly. Can you try it with the current versions or provide more information?

**Comment by Diaphteiros** [comment]
Closed due to inactivity.
