### ISSUE TITLE
Backup garden-setup state

### ISSUE THREAD

**Issue by schrodit** [gardener/garden-setup#71]
**What would you like to be added**:
It would be good if the state of a garden-setup installation (state, export and gen) is backuped somewhere that is not the current local disk. (e.g. S3/GCS or kubernetes itself)

**Why is this needed**:
This is needed to recover or delete a cluster (maybe broken) if the state on the local machine is gone.

**Comment by Diaphteiros** [comment]
Although this could be solved in garden-setup, it would be much cleaner to solve it in `sow` instead. I opened an issue there: https://github.com/gardener/sow/issues/17

**Comment by Diaphteiros** [comment]
This has been solved with sow version `1.1.1` and garden-setup `1.13.0`. See [here](https://github.com/gardener/garden-setup/blob/master/docs/extended/installation-handler.md) for more information.
