### ISSUE TITLE
sow delete doesn't delete the soil cluster

### ISSUE THREAD

**Issue by kayrus** [gardener/garden-setup#75]
**What happened**:

during the shoot deletion the `must have a "confirmation.garden.sapcloud.io/deletion" annotation to delete` error occurs

**What you expected to happen**:

annotation have to be performed automatically

**Comment by Diaphteiros** [comment]
Since release 1.7.0, garden-setup needs `sow` version 1.0.9 or higher, see [release notes](https://github.com/gardener/garden-setup/releases/tag/1.7.0). If you use this version of sow, deletion of shoots should work.
