### ISSUE TITLE
Allow specifying the worker nodes parameters inside the seed definition

### ISSUE THREAD

**Issue by kayrus** [gardener/garden-setup#77]
**What would you like to be added**:

I'd like to have an ability to specify the following k8s cluster parameters:

```
- autoScalerMax: 5
  autoScalerMin: 3
  machineType: m1.xlarge
  maxSurge: 50%
  maxUnavailable: 0
  name: cpu-worker
```

**Comment by Diaphteiros** [comment]
This is possible since release 1.16.0 (https://github.com/gardener/garden-setup/releases/tag/1.16.0).
See https://github.com/gardener/garden-setup/blob/master/docs/extended/iaas.md#worker-configuration for more information.
