### ISSUE TITLE
Print diff before performing a helm upgrade or kubectl apply

### ISSUE THREAD

**Issue by kayrus** [gardener/garden-setup#97]
**What would you like to be added**:

I'd like to see the diff of what is going to be changed during the `helm upgrade` or `kubectl apply -f file.yaml`

**Why is this needed**:

It is not clear what has been changed, e.g.

```
controllerregistration.core.gardener.cloud/dns-external configured
```

or 

```
Running helm upgrade for gardener ...
Release "gardener" has been upgraded. Happy Helming!
```

Some references:
* https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/
* https://github.com/databus23/helm-diff

**Comment by Diaphteiros** [comment]
The point is valid, but I'm closing the issue for now, as we are already working on a tool which will replace garden-setup and the requested enhancement has a low priority and medium effort (I guess), so I don't think this will be added anymore.
